language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl

install:
  curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;

script:
    - cl -l prove -e '(or (prove:run :pffft-test) (uiop:quit -1))'
